= Spring Boot 3.3 - What to keep an eye on?
:toc:
:toc-placement:
:toclevels: 3

Let's take a look at the new observability changes.

== Jersey

* Micrometer 1.13+ requires us to add a dependency on `org.glassfish.jersey.ext:jersey-micrometer` as the Jersey support has been deprecated.
*  `MetricsApplicationEventListener` has been replaced by `ObservationApplicationEventListener`
* tag customization is now handled through a `JerseyObservationConvention` bean rather than `JerseyTagsProvider`


== New properties

We've once again received some observability enhancements.
[cols="1,1,1"]
|===
|Name | Default Value | Description

| spring.rabbitmq.listener.direct.observation-enabled
| false
| Whether to enable observation.

| spring.rabbitmq.listener.simple.observation-enabled
| false
| Whether to enable observation.

| spring.rabbitmq.listener.stream.observation-enabled
| false
| Whether to enable observation.

| spring.rabbitmq.template.observation-enabled
| false
| Whether to enable observation.

|===