= Spring Boot 3.3 - What to keep an eye on?
:toc:
:toc-placement:
:toclevels: 3

Spring Boot 3.3 is releasing on the 23th of May 2024, and one again it contains a lot of useful observability changes.

Observability being a key focus for the Spring team, and production ready application was once again underscored during the latest https://www.youtube.com/watch?v=isAqJYBQz1A[Spring Office Hours] hosted by Dan Vega, Jonathan Ivanov and Tommy Ludwig.

So let's take a look at the new observability changes.

== Rabbit
* observations can be enabled for simple/direct/stream listeners, and on `RabbitTemplate` using <<_new_properties,properties>>.

== Jersey
* Micrometer 1.13+ requires us to add a dependency on `org.glassfish.jersey.ext:jersey-micrometer` as the Jersey support has been deprecated.
* `MetricsApplicationEventListener` has been replaced by `ObservationApplicationEventListener`
* tag customization is now handled through a `JerseyObservationConvention` bean rather than `JerseyTagsProvider`

== Micrometer

*  `@SpanTag` is now supported

== OpenTelemetry
* support for tagged fields has been added

== Brave
** support for tagged and local fields has been added
** upgrade to 6.0

== Zipkin
** upgrade to 3.0 thus enabling us to: define different encodings, dynamic endpoint sources, ...

== Prometheus
Micrometer 1.13 has a new `micrometer-registry-prometheus-simpleclient` module, and uses the 0.16.* version of the Prometheus Java Client. The existing `micrometer-registry-prometheus` module uses the 1.* generation which is *not yet supported by Spring Boot*, so don't forget to switch to the latter module with the former!

If you don't the auto-configuration won't work!

[#_new_properties]
== New properties

We've once again received some observability enhancements.
[cols="1,1,1"]
|===
|Name | Default value | Description

| management.info.process.enabled
| false
| Whether to enable the *new* process `InfoContributor`.

| spring.rabbitmq.listener.direct.observation-enabled
| false
| Whether to enable observation.

| spring.rabbitmq.listener.simple.observation-enabled
| false
| Whether to enable observation.

| spring.rabbitmq.listener.stream.observation-enabled
| false
| Whether to enable observation.

| spring.rabbitmq.template.observation-enabled
| false
| Whether to enable observation.

| management.observations.long-task-timer.enabled
| false
| Whether a LongTaskTimer should be created for every observation.
|===

== Changed properties
[cols="1,1,1,1"]
|===
|Name | New value | Previous value

| spring.pulsar.listener.observation-enabled
| false
| true

| spring.pulsar.template.observations-enabled
| false
| true

|===

== Varia

While not directly observability related, do keep in mind in case you're using Gradle, and the native build tools to build your project for GraalVM you'll need to make certain you're using at least version 0.10.0 of the plugin.